from sympy import im
from analyser.architectures.linear import linear
from analyser.architectures.fully_connected import fully_connected
from analyser.architectures.octagons import octagons
from analyser.architectures.diamonds import diamonds
from analyser.architectures.square_grid import square_grid
from analyser.architectures.circle import circle
from analyser.architectures.big_hexagons import big_hexagons
from analyser.architectures.stack import stack
from analyser.architectures.qubits_to_connections import qubits_to_connections
from analyser.architectures.hexagons import hexagons
from analyser.architectures.minimum_viable import minimum_viable
